CREATE DATABASE IF NOT EXISTS test;

ALTER DATABASE test DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;
	
USE test;

CREATE TABLE IF NOT EXISTS lineitems (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LINE_ITEM_NUMBER VARCHAR(250) NOT NULL,
  NOMENCLATURE VARCHAR(250) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  QUANTITY INT NOT NULL,
  UNIT_PRICE DECIMAL NOT NULL,
  TOTAL_COST DECIMAL NOT NULL
);

--INSERT INTO lineitems (ID, LINE_ITEM_NUMBER, NOMENCLATURE, DESCRIPTION, QUANTITY, UNIT_PRICE, TOTAL_COST) VALUES
--  (100, '0001', 'Building', 'IT Building', 100, 99999, 99999);